Page({
	data:{
		list:[
			{url:'/pages/voice/voice',src:'/images/WechatIMG1336.png',name:'现金红包福利',desc:'关注包你说公众号',text:'马上抢'},
			{url:'/pages/voice/voice',src:'/images/WechatIMG1336.png',name:'欢乐翻盘',desc:'能找到这个红包算你赢',text:'玩一玩'},
			{url:'/pages/voice/voice',src:'/images/WechatIMG1336.png',name:'欢乐拼图',desc:'超级好玩的拼图',text:'玩一玩'},
			{url:'/pages/voice/voice',src:'/images/WechatIMG1336.png',name:'现金红包福利',desc:'关注包你说公众号',text:'马上抢'},
			{url:'/pages/voice/voice',src:'/images/WechatIMG1336.png',name:'现金红包福利',desc:'关注包你说公众号',text:'马上抢'},
			{url:'/pages/voice/voice',src:'/images/WechatIMG1336.png',name:'现金红包福利',desc:'关注包你说公众号',text:'马上抢'},
		]
	}
})